package org.carpetorgaddition.dataupdate;

import com.google.gson.JsonObject;

import java.util.List;

public class CarpetConfDataUpdater implements DataUpdater {
    /**
     * 所有规则，截至{@code 2025年6月19日}
     */
    public static final List<String> OLD_VERSION_RULES = List.of(
            "commandItemShadowing",
            "setBedrockHardness",
            "bindingCurseInvalidation",
            "disableOpenOrWaterDetection",
            "creativeImmuneKill",
            "flyingUseOnBlockFirework",
            "staringEndermanNotAngry",
            "farmlandPreventStepping",
            "maxBlockPlaceDistance",
            "simpleUpdateSkipper",
            "channelingIgnoreWeather",
            "notDamageEnderPearl",
            "disableDamageImmunity",
            "disableBatCanSpawn",
            "turtleEggFastHatch",
            "openShulkerBoxForcibly",
            "villagerInfiniteTrade",
            "fireworkRocketUseCooldown",
            "riptideIgnoreWeather",
            "pickaxeMinedBedrock",
            "villagerHeal",
            "fakePlayerHeal",
            "maxBlockPlaceDistanceReferToEntity",
            "knockbackStick",
            "disableRespawnBlocksExplode",
            "CCEUpdateSuppression",
            "openSeedPermissions",
            "openCarpetPermissions",
            "openGameRulePermissions",
            "openVillagerInventory",
            "peacefulCreeper",
            "commandXpTransfer",
            "commandSpectator",
            "commandFinder",
            "commandKillMe",
            "commandLocations",
            "healthNotFullCanEat",
            "canMineSpawner",
            "fakePlayerSpawnNoKnockback",
            "canActivatesObserver",
            "disableWaterFreezes",
            "fakePlayerCraftKeepItem",
            "commandParticleLine",
            "disableMobPeacefulDespawn",
            "climbingBoat",
            "reusableSmithingTemplate",
            "openTpPermissions",
            "softDeepslate",
            "softObsidian",
            "softOres",
            "betterTotemOfUndying",
            "commandPlayerAction",
            "fakePlayerCraftPickItemFromShulkerBox",
            "customPiglinBarteringTime",
            "quickSettingFakePlayerCraft",
            "fakePlayerKeepInventory",
            "commandCreeper",
            "commandRuleSearch",
            "superChargedCreeper",
            "playerDropHead",
            "beaconRangeExpand",
            "beaconWorldHeight",
            "canHighlightBlockPos",
            "commandPlayerManager",
            "blockDropsDirectlyEnterInventory",
            "turtleEggFastMine",
            "commandNavigate",
            "playerDropsNotDespawning",
            "fakePlayerMaxCraftCount",
            "fakePlayerSpawnMemoryLeakFix",
            "commandMail",
            "suppressionMismatchInDestroyBlockPosWarn",
            "syncNavigateWaypoint",
            "shulkerBoxStackable",
            "maxBlockPlaceDistanceSyncClient",
            "limitPhantomSpawn",
            "applyToolEffectsImmediately",
            "forceRestock",
            "autoSyncPlayerStatus",
            "recordPlayerCommand",
            "protectionEnchantmentCompatible",
            "damageEnchantmentCompatible",
            "finderCommandMaxFeedbackCount",
            "totemOfUndyingInvincibleTime",
            "playerCommandOpenPlayerInventory",
            "playerCommandTeleportFakePlayer",
            "experienceOrbMerge",
            "quickShulker",
            "disableCreativeContainerDrops"
    );

    @Override
    public JsonObject update(JsonObject json, int version) {
        return json;
    }
}
